In [1]:
import numpy as np
import pandas as pd
import pyarrow as pa
import matplotlib.pyplot as plt
import seaborn as sns
from IPython.display import display

pd.set_option("display.max_columns", None)
pd.set_option('display.float_format', lambda x: '%.3f' % x)
from pandas.tseries.offsets import MonthEnd, MonthBegin

In [2]:
import sys
from pathlib import Path

# Add the project root directory to sys.path
# (Adjust .parent counts depending on how deep your notebook is)
project_root = Path.cwd().parent
if str(project_root) not in sys.path:
    sys.path.append(str(project_root))

# Now import directly from your folder structure
from scripts.data_cleaning import clean_data, add_columns

In [33]:
df = pd.read_parquet(f"https://d37ci6vzurychx.cloudfront.net/trip-data/yellow_tripdata_2023-09.parquet")

In [27]:
# df.sort_values('tpep_pickup_datetime').head(40)

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge,Airport_fee
1366103,2,2008-12-31 15:05:04,2008-12-31 16:18:04,1.000,11.770,1.000,N,230,138,1,68.800,5.000,0.500,16.450,6.940,1.000,98.690,0.000,0.000
70438,2,2008-12-31 20:41:22,2008-12-31 21:03:22,1.000,6.460,1.000,N,162,264,1,28.900,1.000,0.500,6.780,0.000,1.000,40.680,2.500,0.000
1250266,2,2009-01-01 00:02:43,2009-01-01 00:04:43,1.000,0.000,1.000,N,7,7,3,-3.000,0.000,-0.500,0.000,0.000,-1.000,-4.500,0.000,0.000
1250267,2,2009-01-01 00:02:43,2009-01-01 00:04:43,1.000,0.000,1.000,N,7,7,3,3.000,0.000,0.500,0.000,0.000,1.000,4.500,0.000,0.000
1932194,2,2009-01-01 00:06:35,2009-01-01 02:22:53,5.000,4.480,1.000,N,161,74,1,21.200,1.000,0.500,6.550,0.000,1.000,32.750,2.500,0.000
13006,2,2009-01-01 07:07:04,2009-01-01 08:33:41,1.000,3.070,1.000,N,170,141,1,20.500,0.000,0.500,4.900,0.000,1.000,29.400,2.500,0.000
379,2,2023-08-31 23:48:03,2023-09-01 00:05:58,1.000,3.650,1.000,N,48,145,1,19.800,1.000,0.500,2.200,0.000,1.000,27.000,2.500,0.000
1847,2,2023-08-31 23:56:00,2023-09-01 00:14:49,3.000,8.660,1.000,N,138,42,2,35.200,6.000,0.500,0.000,6.940,1.000,51.390,0.000,1.750
119,2,2023-08-31 23:56:01,2023-09-01 00:18:41,1.000,3.110,1.000,N,114,246,1,21.200,1.000,0.500,0.000,0.000,1.000,26.200,2.500,0.000
618,2,2023-08-31 23:56:28,2023-09-01 00:16:56,1.000,3.540,1.000,N,48,249,1,20.500,1.000,0.500,2.000,0.000,1.000,27.500,2.500,0.000
318,2,2023-08-31 23:56:48,2023-09-01 00:18:33,5.000,4.400,1.000,N,186,24,1,24.000,1.000,0.500,5.800,0.000,1.000,34.800,2.500,0.000
442,2,2023-08-31 23:57:10,2023-09-01 00:03:18,2.000,1.270,1.000,N,230,143,1,8.600,1.000,0.500,2.720,0.000,1.000,16.320,2.500,0.000
206,2,2023-08-31 23:57:50,2023-09-01 00:27:33,2.000,5.570,1.000,N,100,7,1,31.000,1.000,0.500,7.200,0.000,1.000,43.200,2.500,0.000
1250,2,2023-08-31 23:58:11,2023-09-01 00:44:40,1.000,18.460,2.000,N,132,68,2,70.000,0.000,0.500,0.000,6.940,1.000,82.690,2.500,1.750
1335,2,2023-08-31 23:58:32,2023-09-01 00:09:05,1.000,1.940,1.000,N,234,162,1,12.100,1.000,0.500,3.420,0.000,1.000,20.520,2.500,0.000
1192,2,2023-08-31 23:58:44,2023-09-01 00:00:52,5.000,0.710,1.000,N,68,246,1,5.100,1.000,0.500,2.500,0.000,1.000,12.600,2.500,0.000
2526,2,2023-08-31 23:58:48,2023-09-01 00:23:13,1.000,1.840,1.000,N,68,107,1,19.800,1.000,0.500,2.000,0.000,1.000,26.800,2.500,0.000
281,2,2023-08-31 23:59:18,2023-09-01 00:20:18,1.000,10.020,1.000,N,138,189,1,40.100,6.000,0.500,9.870,0.000,1.000,59.220,0.000,1.750
1972,2,2023-08-31 23:59:27,2023-09-01 00:06:07,1.000,1.550,1.000,N,113,45,2,10.000,1.000,0.500,0.000,0.000,1.000,15.000,2.500,0.000
579,2,2023-08-31 23:59:29,2023-09-01 00:30:20,1.000,12.080,1.000,N,70,186,1,50.600,6.000,0.500,12.470,0.000,1.000,74.820,2.500,1.750
1318,2,2023-08-31 23:59:43,2023-09-01 00:15:59,1.000,3.160,1.000,N,48,262,1,17.700,1.000,0.500,4.540,0.000,1.000,27.240,2.500,0.000
2182,2,2023-08-31 23:59:51,2023-09-01 00:09:36,1.000,1.270,1.000,N,48,230,2,10.700,1.000,0.500,0.000,0.000,1.000,15.700,2.500,0.000
432,2,2023-08-31 23:59:51,2023-09-01 00:18:54,5.000,3.420,1.000,N,249,48,1,20.500,1.000,0.500,5.100,0.000,1.000,30.600,2.500,0.000
564,2,2023-08-31 23:59:58,2023-09-01 00:15:27,1.000,2.840,1.000,N,162,144,1,17.000,1.000,0.500,4.400,0.000,1.000,26.400,2.500,0.000
391,1,2023-09-01 00:00:00,2023-09-01 00:19:26,2.000,10.000,1.000,N,138,4,1,39.400,10.250,0.500,12.750,0.000,1.000,63.900,2.500,1.750
2706532,1,2023-09-01 00:00:01,2023-09-01 00:16:12,NaN,0.000,NaN,None,186,141,0,18.210,0.000,0.500,0.000,0.000,1.000,22.210,NaN,NaN
1876,2,2023-09-01 00:00:02,2023-09-01 00:14:04,1.000,3.010,1.000,N,234,13,1,16.300,1.000,0.500,3.200,0.000,1.000,24.500,2.500,0.000
1697,2,2023-09-01 00:00:07,2023-09-01 00:06:45,1.000,0.930,1.000,N,114,107,1,8.600,1.000,0.500,1.000,0.000,1.000,14.600,2.500,0.000
2114,2,2023-09-01 00:00:09,2023-09-01 00:03:56,1.000,0.670,1.000,N,211,114,1,6.500,1.000,0.500,2.300,0.000,1.000,13.800,2.500,0.000
136,1,2023-09-01 00:00:13,2023-09-01 00:27:12,1.000,0.000,99.000,N,48,98,1,38.500,0.000,0.500,0.000,6.940,1.000,46.940,0.000,0.000
1311,2,2023-09-01 00:00:14,2023-09-01 00:11:16,2.000,1.920,1.000,N,100,143,1,12.800,1.000,0.500,3.000,0.000,1.000,20.800,2.500,0.000
260,2,2023-09-01 00:00:14,2023-09-01 00:35:21,1.000,19.990,1.000,N,132,14,1,78.600,1.000,0.500,16.220,0.000,1.000,99.070,0.000,1.750
2228,2,2023-09-01 00:00:16,2023-09-01 00:19:40,1.000,10.020,1.000,N,132,56,2,40.100,1.000,0.500,0.000,0.000,1.000,44.350,0.000,1.750
315,1,2023-09-01 00:00:18,2023-09-01 00:40:30,1.000,0.000,1.000,N,75,225,1,51.500,0.000,0.500,0.000,6.940,1.000,59.940,0.000,0.000
968,2,2023-09-01 00:00:19,2023-09-01 00:06:07,1.000,0.570,1.000,N,170,170,2,7.200,1.000,0.500,0.000,0.000,1.000,12.200,2.500,0.000
2706537,2,2023-09-01 00:00:20,2023-09-01 00:21:21,NaN,4.890,NaN,None,239,114,0,26.660,0.000,0.500,3.070,0.000,1.000,33.730,NaN,NaN
515,1,2023-09-01 00:00:20,2023-09-01 00:02:17,1.000,0.500,1.000,N,48,48,1,5.100,3.500,0.500,0.000,0.000,1.000,10.100,2.500,0.000
514,2,2023-09-01 00:00:21,2023-09-01 00:21:26,1.000,9.790,1.000,N,132,56,2,38.000,1.000,0.500,0.000,0.000,1.000,42.250,0.000,1.750
960,2,2023-09-01 00:00:21,2023-09-01 00:10:08,1.000,2.500,1.000,N,141,48,1,13.500,1.000,0.500,5.550,0.000,1.000,24.050,2.500,0.000
2482,1,2023-09-01 00:00:21,2023-09-01 00:30:21,1.000,22.100,1.000,N,132,14,2,80.700,2.750,0.500,0.000,0.000,1.000,84.950,0.000,1.750

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3066766 entries, 0 to 3066765
Data columns (total 19 columns):
 #   Column                 Dtype
---  ------                 -----
 0   VendorID               int64
 1   tpep_pickup_datetime   datetime64[us]
 2   tpep_dropoff_datetime  datetime64[us]
 3   passenger_count        float64
 4   trip_distance          float64
 5   RatecodeID             float64
 6   store_and_fwd_flag     object
 7   PULocationID           int64
 8   DOLocationID           int64
 9   payment_type           int64
 10  fare_amount            float64
 11  extra                  float64
 12  mta_tax                float64
 13  tip_amount             float64
 14  tolls_amount           float64
 15  improvement_surcharge  float64
 16  total_amount           float64
 17  congestion_surcharge   float64
 18  airport_fee            float64
dtypes: datetime64[us](2), float64(12), int64(4), object(1)
memory usage: 444.6+ MB

In [34]:
df['tpep_pickup_datetime'].dt.date.value_counts()

tpep_pickup_datetime
2023-09-07    129391
2023-09-28    127429
2023-09-14    125129
2023-09-08    124668
2023-09-27    119199
2023-09-12    119000
2023-09-13    118623
2023-09-06    117759
2023-09-09    117255
2023-09-15    116571
2023-09-30    113243
2023-09-26    112520
2023-09-16    111808
2023-09-20    108434
2023-09-11    107401
2023-09-10    105142
2023-09-29    105091
2023-09-19    104565
2023-09-05    102694
2023-09-18     96460
2023-09-17     95051
2023-09-25     91341
2023-09-01     86684
2023-09-02     82424
2023-09-03     79000
2023-09-04     72691
2023-09-21     41939
2023-09-23      5732
2023-09-24      4813
2023-09-22      4633
2023-08-31        18
2023-10-01         8
2009-01-01         4
2008-12-31         2
Name: count, dtype: int64

In [35]:
df_org = df.copy()

In [36]:
df = clean_data(df, 9)[0]

In [37]:
df['tpep_pickup_datetime'].dt.date.value_counts()

tpep_pickup_datetime
2023-09-07    120671
2023-09-28    117582
2023-09-14    116753
2023-09-08    114746
2023-09-13    110775
2023-09-27    110655
2023-09-12    110492
2023-09-06    110230
2023-09-15    107967
2023-09-09    107958
2023-09-30    104533
2023-09-26    104363
2023-09-16    102104
2023-09-20    100658
2023-09-11     99143
2023-09-19     96758
2023-09-05     96228
2023-09-10     95173
2023-09-29     92427
2023-09-18     88349
2023-09-17     86236
2023-09-25     84693
2023-09-01     80885
2023-09-02     76828
2023-09-03     72844
2023-09-04     67060
2023-09-21     36090
2023-09-24        95
2023-09-22        20
2023-09-23        16
Name: count, dtype: int64

In [8]:
df_org.shape

(3066766, 19)

In [9]:
df.shape

(2897040, 29)

In [21]:
(df_org['tpep_pickup_datetime'].dt.date).value_counts()

tpep_pickup_datetime
2023-01-26    114877
2023-01-19    114603
2023-01-14    112950
2023-01-21    111999
2023-01-27    111668
2023-01-28    111645
2023-01-12    111386
2023-01-13    110719
2023-01-20    109444
2023-01-25    109196
2023-01-18    106152
2023-01-11    106118
2023-01-07    105036
2023-01-24    103858
2023-01-06    102550
2023-01-05    101063
2023-01-17    101052
2023-01-31    100372
2023-01-10     99916
2023-01-15     96844
2023-01-04     95092
2023-01-23     89791
2023-01-22     89651
2023-01-29     88131
2023-01-03     85783
2023-01-09     85349
2023-01-08     85056
2023-01-30     83768
2023-01-16     80120
2023-01-01     76752
2023-01-02     65777
2022-12-31        25
2023-02-01        10
2022-10-25         7
2022-10-24         4
2008-12-31         2
Name: count, dtype: int64

In [11]:
df_org['pickup_date'] = df_org['tpep_pickup_datetime'].dt.date

In [12]:
df_org[df_org['pickup_date'].astype('str') == "2023-03-31"]

Empty DataFrame
Columns: [VendorID, tpep_pickup_datetime, tpep_dropoff_datetime, passenger_count, trip_distance, RatecodeID, store_and_fwd_flag, PULocationID, DOLocationID, payment_type, fare_amount, extra, mta_tax, tip_amount, tolls_amount, improvement_surcharge, total_amount, congestion_surcharge, airport_fee, pickup_date]
Index: []

In [13]:
df_org['pickup_date']

0          2023-01-01
1          2023-01-01
2          2023-01-01
3          2023-01-01
4          2023-01-01
              ...
3066761    2023-01-31
3066762    2023-01-31
3066763    2023-01-31
3066764    2023-01-31
3066765    2023-01-31
Name: pickup_date, Length: 3066766, dtype: object

In [14]:
month_start = pd.Timestamp(
    year=2023,
    month=4,
    day=1
)

month_end = (month_start + MonthEnd(1)).replace(hour=23, minute=59, second=59)

In [15]:
month_start

Timestamp('2023-04-01 00:00:00')

In [16]:
month_end

Timestamp('2023-04-30 23:59:59')

In [17]:
def fix_date_cols(df, tz='UTC'):
    cols = df.select_dtypes(include=['datetime64']).columns
    for col in cols:
        df[col] = df[col].dt.tz_localize(tz)

In [18]:
fix_date_cols(df)

In [19]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 2897040 entries, 0 to 2995022
Data columns (total 29 columns):
 #   Column                  Dtype
---  ------                  -----
 0   VendorID                int64
 1   tpep_pickup_datetime    datetime64[us, UTC]
 2   tpep_dropoff_datetime   datetime64[us, UTC]
 3   passenger_count         float64
 4   trip_distance           float64
 5   RatecodeID              float64
 6   store_and_fwd_flag      object
 7   PULocationID            int64
 8   DOLocationID            int64
 9   payment_type            int64
 10  fare_amount             float64
 11  extra                   float64
 12  mta_tax                 float64
 13  tip_amount              float64
 14  tolls_amount            float64
 15  improvement_surcharge   float64
 16  total_amount            float64
 17  congestion_surcharge    float64
 18  airport_fee             float64
 19  abs_fare                float64
 20  abs_total               float64
 21  pickup_month            int32
 22  pickup_day              int32
 23  pickup_hour             int32
 24  pickup_day_of_week_num  int32
 25  pickup_day_of_week      object
 26  pickup_date             object
 27  is_weekend              bool
 28  trip_duration_minutes   float64
dtypes: bool(1), datetime64[us, UTC](2), float64(15), int32(4), int64(4), object(3)
memory usage: 599.5+ MB

In [20]:
df.sort_values('tpep_pickup_datetime').head()

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge,airport_fee,abs_fare,abs_total,pickup_month,pickup_day,pickup_hour,pickup_day_of_week_num,pickup_day_of_week,pickup_date,is_weekend,trip_duration_minutes
3497,2,2023-01-01 00:00:05+00:00,2023-01-01 00:26:27+00:00,1.000,1.320,1.000,N,249,186,2,21.900,1.000,0.500,0.000,0.000,1.000,26.900,2.500,0.000,21.900,26.900,1,1,0,6,Sunday,2023-01-01,True,26.367
2506,2,2023-01-01 00:00:06+00:00,2023-01-01 00:05:44+00:00,1.000,1.700,1.000,N,125,68,2,9.300,1.000,0.500,0.000,0.000,1.000,14.300,2.500,0.000,9.300,14.300,1,1,0,6,Sunday,2023-01-01,True,5.633
3499,2,2023-01-01 00:00:08+00:00,2023-01-01 00:11:24+00:00,1.000,3.100,1.000,N,42,244,2,16.300,1.000,0.500,0.000,0.000,1.000,18.800,0.000,0.000,16.300,18.800,1,1,0,6,Sunday,2023-01-01,True,11.267
4475,2,2023-01-01 00:00:09+00:00,2023-01-01 00:15:10+00:00,1.000,3.800,1.000,N,79,231,1,19.800,1.000,0.500,7.440,0.000,1.000,32.240,2.500,0.000,19.800,32.240,1,1,0,6,Sunday,2023-01-01,True,15.017
3176,2,2023-01-01 00:00:13+00:00,2023-01-01 00:12:52+00:00,1.000,8.970,1.000,N,132,7,1,34.500,1.000,0.500,25.000,0.000,1.000,63.250,0.000,1.250,34.500,63.250,1,1,0,6,Sunday,2023-01-01,True,12.650