In [1]:
import numpy as np
import pandas as pd
import pyarrow as pa
import matplotlib.pyplot as plt
import seaborn as sns
from IPython.display import display

pd.set_option("display.max_columns", None)
pd.set_option('display.float_format', lambda x: '%.3f' % x)

In [2]:
import sys
from pathlib import Path

# Add the project root directory to sys.path
# (Adjust .parent counts depending on how deep your notebook is)
project_root = Path.cwd().parent
if str(project_root) not in sys.path:
    sys.path.append(str(project_root))

# Now import directly from your folder structure
from scripts.data_cleaning import clean_data, add_columns

In [3]:
month_name_num = {
    "Jan": "01",
    "Feb": "02",
    "Mar": "03",
    "Apr": "04",
    "May": "05",
    "Jun": "06",
    "Jul": "07",
    "Aug": "08",
    "Sep": "09",
    "Oct": "10",
    "Nov": "11",
    "Dec": "12",
}

In [4]:
monthly_data = {}

In [5]:
for key, value in month_name_num.items():
    df = pd.read_parquet(f"https://d37ci6vzurychx.cloudfront.net/trip-data/yellow_tripdata_2023-{value}.parquet")
    cleaned_df = clean_data(df, int(value))
    monthly_data[key] = cleaned_df

In [7]:
df_jan = monthly_data['Jan'][0]

In [8]:
df_jan.head()

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge,airport_fee,abs_fare,abs_total,pickup_month,pickup_day,pickup_hour,pickup_day_of_week_num,pickup_day_of_week,pickup_date,is_weekend,trip_duration_minutes
0,2,2023-01-01 00:32:10,2023-01-01 00:40:36,1.000,0.970,1.000,N,161,141,2,9.300,1.000,0.500,0.000,0.000,1.000,14.300,2.500,0.000,9.300,14.300,1,1,0,6,Sunday,2023-01-01,True,8.433
1,2,2023-01-01 00:55:08,2023-01-01 01:01:27,1.000,1.100,1.000,N,43,237,1,7.900,1.000,0.500,4.000,0.000,1.000,16.900,2.500,0.000,7.900,16.900,1,1,0,6,Sunday,2023-01-01,True,6.317
2,2,2023-01-01 00:25:04,2023-01-01 00:37:49,1.000,2.510,1.000,N,48,238,1,14.900,1.000,0.500,15.000,0.000,1.000,34.900,2.500,0.000,14.900,34.900,1,1,0,6,Sunday,2023-01-01,True,12.750
4,2,2023-01-01 00:10:29,2023-01-01 00:21:19,1.000,1.430,1.000,N,107,79,1,11.400,1.000,0.500,3.280,0.000,1.000,19.680,2.500,0.000,11.400,19.680,1,1,0,6,Sunday,2023-01-01,True,10.833
5,2,2023-01-01 00:50:34,2023-01-01 01:02:52,1.000,1.840,1.000,N,161,137,1,12.800,1.000,0.500,10.000,0.000,1.000,27.800,2.500,0.000,12.800,27.800,1,1,0,6,Sunday,2023-01-01,True,12.300

In [9]:
# df_jan['pickup_month'] = df_jan['tpep_pickup_datetime'].dt.month
# df_jan['pickup_day'] = df_jan['tpep_pickup_datetime'].dt.day
# df_jan['pickup_hour'] = df_jan['tpep_pickup_datetime'].dt.hour
# df_jan['pickup_day_of_week_num'] = df_jan['tpep_pickup_datetime'].dt.day_of_week
# df_jan['pickup_day_of_week'] = df_jan['tpep_pickup_datetime'].dt.day_name()
# df_jan['pickup_date'] = df_jan['tpep_pickup_datetime'].dt.date
# df_jan["is_weekend"] = (
#     df_jan["pickup_day_of_week_num"] >= 5
# )
# df_jan['trip_duration_minutes'] = (
#         df_jan["tpep_dropoff_datetime"]
#         - df_jan["tpep_pickup_datetime"]
#     ).dt.total_seconds() / 60

In [10]:
df_jan.head()

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge,airport_fee,abs_fare,abs_total,pickup_month,pickup_day,pickup_hour,pickup_day_of_week_num,pickup_day_of_week,pickup_date,is_weekend,trip_duration_minutes
0,2,2023-01-01 00:32:10,2023-01-01 00:40:36,1.000,0.970,1.000,N,161,141,2,9.300,1.000,0.500,0.000,0.000,1.000,14.300,2.500,0.000,9.300,14.300,1,1,0,6,Sunday,2023-01-01,True,8.433
1,2,2023-01-01 00:55:08,2023-01-01 01:01:27,1.000,1.100,1.000,N,43,237,1,7.900,1.000,0.500,4.000,0.000,1.000,16.900,2.500,0.000,7.900,16.900,1,1,0,6,Sunday,2023-01-01,True,6.317
2,2,2023-01-01 00:25:04,2023-01-01 00:37:49,1.000,2.510,1.000,N,48,238,1,14.900,1.000,0.500,15.000,0.000,1.000,34.900,2.500,0.000,14.900,34.900,1,1,0,6,Sunday,2023-01-01,True,12.750
4,2,2023-01-01 00:10:29,2023-01-01 00:21:19,1.000,1.430,1.000,N,107,79,1,11.400,1.000,0.500,3.280,0.000,1.000,19.680,2.500,0.000,11.400,19.680,1,1,0,6,Sunday,2023-01-01,True,10.833
5,2,2023-01-01 00:50:34,2023-01-01 01:02:52,1.000,1.840,1.000,N,161,137,1,12.800,1.000,0.500,10.000,0.000,1.000,27.800,2.500,0.000,12.800,27.800,1,1,0,6,Sunday,2023-01-01,True,12.300

In [11]:
df_jan.describe()

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,PULocationID,DOLocationID,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge,airport_fee,abs_fare,abs_total,pickup_month,pickup_day,pickup_hour,pickup_day_of_week_num,trip_duration_minutes
count,2802015.000,2802015,2802015,2802015.000,2802015.000,2802015.000,2802015.000,2802015.000,2802015.000,2802015.000,2802015.000,2802015.000,2802015.000,2802015.000,2802015.000,2802015.000,2802015.000,2802015.000,2802015.000,2802015.000,2802015.000,2802015.000,2802015.000,2802015.000,2802015.000
mean,1.741,2023-01-16 12:49:22.801482,2023-01-16 13:05:07.383828,1.390,3.399,1.506,166.372,164.429,1.189,18.680,1.561,0.496,3.421,0.536,0.999,27.498,2.312,0.111,18.680,27.498,1.000,15.924,14.151,3.070,15.743
min,1.000,2023-01-01 00:00:05,2023-01-01 00:03:28,1.000,0.000,1.000,1.000,1.000,1.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,1.000,1.000,0.000,0.000,0.000
25%,1.000,2023-01-09 11:55:40,2023-01-09 12:11:18.500000,1.000,1.080,1.000,132.000,114.000,1.000,8.600,0.000,0.500,1.000,0.000,1.000,15.480,2.500,0.000,8.600,15.480,1.000,9.000,11.000,1.000,7.133
50%,2.000,2023-01-16 15:45:33,2023-01-16 16:01:53,1.000,1.800,1.000,162.000,162.000,1.000,12.800,1.000,0.500,2.800,0.000,1.000,20.160,2.500,0.000,12.800,20.160,1.000,16.000,15.000,3.000,11.500
75%,2.000,2023-01-23 19:28:44,2023-01-23 19:41:41,1.000,3.340,1.000,234.000,234.000,1.000,20.500,2.500,0.500,4.200,0.000,1.000,28.800,2.500,0.000,20.500,28.800,1.000,23.000,19.000,5.000,18.250
max,2.000,2023-01-30 23:59:58,2023-01-31 21:58:49,9.000,96.700,99.000,265.000,265.000,4.000,999.000,12.500,53.160,380.800,196.990,1.000,1000.000,2.500,1.250,999.000,1000.000,1.000,30.000,23.000,6.000,10029.183
std,0.438,NaN,NaN,0.890,4.423,6.541,64.126,69.980,0.413,17.448,1.776,0.054,3.855,2.031,0.033,21.761,0.659,0.355,17.448,21.761,0.000,8.410,5.772,1.988,43.838

## ~~Need to go back to cleaning. Some dates are reversed for pickup and dropoff.~~ Completed

In [12]:
# def add_columns(df):
#     df['pickup_month'] = df['tpep_pickup_datetime'].dt.month
#     df['pickup_day'] = df['tpep_pickup_datetime'].dt.day
#     df['pickup_hour'] = df['tpep_pickup_datetime'].dt.hour
#     df['pickup_day_of_week_num'] = df['tpep_pickup_datetime'].dt.day_of_week
#     df['pickup_day_of_week'] = df['tpep_pickup_datetime'].dt.day_name()
#     df['pickup_date'] = df['tpep_pickup_datetime'].dt.date
#     df["is_weekend"] = (
#         df["pickup_day_of_week_num"] >= 5
#     )
#     df['trip_duration_minutes'] = (
#             df["tpep_dropoff_datetime"]
#             - df["tpep_pickup_datetime"]
#         ).dt.total_seconds() / 60

#     return df

In [13]:
df_feb = monthly_data['Feb'][0]

In [14]:
df_feb.describe()

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,PULocationID,DOLocationID,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge,airport_fee,abs_fare,abs_total,pickup_month,pickup_day,pickup_hour,pickup_day_of_week_num,trip_duration_minutes
count,2648400.000,2648400,2648400,2648400.000,2648400.000,2648400.000,2648400.000,2648400.000,2648400.000,2648400.000,2648400.000,2648400.000,2648400.000,2648400.000,2648400.000,2648400.000,2648400.000,2648400.000,2648400.000,2648400.000,2648400.000,2648400.000,2648400.000,2648400.000,2648400.000
mean,1.738,2023-02-14 13:17:48.418519,2023-02-14 13:33:54.185815,1.379,3.305,1.529,166.298,164.370,1.179,18.543,1.591,0.496,3.446,0.522,0.999,27.395,2.326,0.099,18.543,27.395,2.000,13.937,14.299,3.090,16.096
min,1.000,2023-02-01 00:00:02,2023-02-01 00:03:10,1.000,0.000,1.000,1.000,1.000,1.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,2.000,1.000,0.000,0.000,0.000
25%,1.000,2023-02-07 21:44:38,2023-02-07 21:58:08.250000,1.000,1.070,1.000,132.000,113.000,1.000,9.300,0.000,0.500,1.000,0.000,1.000,15.600,2.500,0.000,9.300,15.600,2.000,7.000,11.000,2.000,7.283
50%,2.000,2023-02-14 15:40:58,2023-02-14 15:59:40.500000,1.000,1.780,1.000,162.000,162.000,1.000,12.800,1.000,0.500,2.800,0.000,1.000,20.300,2.500,0.000,12.800,20.300,2.000,14.000,15.000,3.000,11.767
75%,2.000,2023-02-21 13:10:06.250000,2023-02-21 13:27:30,1.000,3.260,1.000,234.000,234.000,1.000,20.500,2.500,0.500,4.260,0.000,1.000,28.920,2.500,0.000,20.500,28.920,2.000,21.000,19.000,5.000,18.700
max,2.000,2023-02-27 23:59:58,2023-02-28 23:14:44,9.000,95.890,99.000,265.000,265.000,4.000,2203.100,13.750,4.000,482.900,109.900,1.000,2208.100,2.750,1.250,2203.100,2208.100,2.000,27.000,23.000,6.000,7053.617
std,0.440,NaN,NaN,0.882,4.300,6.751,63.935,69.746,0.405,17.068,1.776,0.044,3.864,2.025,0.033,21.353,0.636,0.337,17.068,21.353,0.000,7.767,5.737,1.913,44.068

In [15]:
df_feb.isna().sum()

VendorID                  0
tpep_pickup_datetime      0
tpep_dropoff_datetime     0
passenger_count           0
trip_distance             0
RatecodeID                0
store_and_fwd_flag        0
PULocationID              0
DOLocationID              0
payment_type              0
fare_amount               0
extra                     0
mta_tax                   0
tip_amount                0
tolls_amount              0
improvement_surcharge     0
total_amount              0
congestion_surcharge      0
airport_fee               0
abs_fare                  0
abs_total                 0
pickup_month              0
pickup_day                0
pickup_hour               0
pickup_day_of_week_num    0
pickup_day_of_week        0
pickup_date               0
is_weekend                0
trip_duration_minutes     0
dtype: int64

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge,airport_fee,abs_fare,abs_total
2,1,2023-03-01 00:15:04,2023-03-01 00:29:26,0.000,3.300,1.000,N,140,186,1,18.400,3.500,0.500,4.650,0.000,1.000,28.050,2.500,0.000,18.400,28.050
69,1,2023-03-01 00:40:02,2023-03-01 00:48:36,0.000,4.100,1.000,N,132,216,2,17.700,2.250,0.500,0.000,0.000,1.000,21.450,0.000,1.250,17.700,21.450
284,1,2023-03-01 00:48:34,2023-03-01 00:59:42,0.000,3.100,1.000,N,231,161,1,15.600,3.500,0.500,4.100,0.000,1.000,24.700,2.500,0.000,15.600,24.700
308,1,2023-03-01 00:08:27,2023-03-01 00:13:14,0.000,0.800,1.000,N,162,164,1,6.500,3.500,0.500,2.300,0.000,1.000,13.800,2.500,0.000,6.500,13.800
396,2,2023-03-01 00:23:47,2023-03-01 01:04:51,0.000,29.120,5.000,N,68,265,1,90.000,0.000,0.500,0.100,0.000,1.000,91.600,0.000,0.000,90.000,91.600
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3203585,1,2023-03-30 23:05:34,2023-03-30 23:52:20,0.000,14.600,2.000,N,216,42,1,70.000,0.000,0.500,15.600,6.550,1.000,93.650,0.000,0.000,70.000,93.650
3203608,1,2023-03-30 23:29:19,2023-03-30 23:35:08,0.000,0.700,1.000,N,79,148,3,7.200,3.500,0.500,0.000,0.000,1.000,12.200,2.500,0.000,7.200,12.200
3203609,1,2023-03-30 23:42:37,2023-03-30 23:52:55,0.000,1.200,1.000,N,113,249,1,10.700,3.500,0.500,3.140,0.000,1.000,18.840,2.500,0.000,10.700,18.840
3203786,1,2023-03-30 23:03:50,2023-03-30 23:38:46,0.000,11.500,1.000,N,132,138,2,54.100,7.250,0.500,0.000,0.000,1.000,62.850,0.000,1.250,54.100,62.850
3203807,1,2023-03-30 23:48:27,2023-03-31 00:06:40,0.000,4.200,1.000,N,41,163,1,21.200,3.500,0.500,5.200,0.000,1.000,31.400,2.500,0.000,21.200,31.400

[         VendorID tpep_pickup_datetime tpep_dropoff_datetime  passenger_count  \
 0               2  2023-01-01 00:32:10   2023-01-01 00:40:36            1.000
 1               2  2023-01-01 00:55:08   2023-01-01 01:01:27            1.000
 2               2  2023-01-01 00:25:04   2023-01-01 00:37:49            1.000
 4               2  2023-01-01 00:10:29   2023-01-01 00:21:19            1.000
 5               2  2023-01-01 00:50:34   2023-01-01 01:02:52            1.000
 ...           ...                  ...                   ...              ...
 2897848         2  2023-01-30 23:57:07   2023-01-31 00:19:26            1.000
 2897926         2  2023-01-30 23:59:21   2023-01-31 00:12:55            5.000
 2897995         2  2023-01-30 23:59:15   2023-01-31 00:07:23            1.000
 2898263         2  2023-01-30 15:15:27   2023-01-30 15:20:29            1.000
 2898349         2  2023-01-30 22:44:25   2023-01-30 22:48:15            1.000

          trip_distance  RatecodeID store_and_fwd_flag  PULocationID  \
 0                0.970       1.000                  N           161
 1                1.100       1.000                  N            43
 2                2.510       1.000                  N            48
 4                1.430       1.000                  N           107
 5                1.840       1.000                  N           161
 ...                ...         ...                ...           ...
 2897848          8.010       1.000                  N           263
 2897926          7.350       1.000                  N           138
 2897995          1.860       1.000                  N           236
 2898263          0.690       1.000                  N           100
 2898349          0.870       1.000                  N           162

          DOLocationID  payment_type  fare_amount  extra  mta_tax  tip_amount  \
 0                 141             2        9.300  1.000    0.500       0.000
 1                 237             1        7.900  1.000    0.500       4.000
 2                 238             1       14.900  1.000    0.500      15.000
 4                  79             1       11.400  1.000    0.500       3.280
 5                 137             1       12.800  1.000    0.500      10.000
 ...               ...           ...          ...    ...      ...         ...
 2897848           209             1       35.200  1.000    0.500       5.500
 2897926           255             1       28.900  6.000    0.500       3.000
 2897995            74             1       10.700  1.000    0.500       3.920
 2898263           230             1        6.500  1.000    0.500       2.300
 2898349           141             2        6.500  1.000    0.500       0.000

          tolls_amount  improvement_surcharge  total_amount  \
 0               0.000                  1.000        14.300
 1               0.000                  1.000        16.900
 2               0.000                  1.000        34.900
 4               0.000                  1.000        19.680
 5               0.000                  1.000        27.800
 ...               ...                    ...           ...
 2897848         0.000                  1.000        45.700
 2897926         0.000                  1.000        40.650
 2897995         0.000                  1.000        19.620
 2898263         0.000                  1.000        13.800
 2898349         0.000                  1.000        11.500

          congestion_surcharge  airport_fee  abs_fare  abs_total  pickup_month  \
 0                       2.500        0.000     9.300     14.300             1
 1                       2.500        0.000     7.900     16.900             1
 2                       2.500        0.000    14.900     34.900             1
 4                       2.500        0.000    11.400     19.680             1
 5                       2.500        0.000    12.800     27.800             1
 ...                       ...          ...       ...        ...           ...
 2897848                 2.500        0.000    35.200     45.700             1
 2897926                 0.000        1.250    28.900     40.650             1
 2897995                 2.500        0.000    10.700     19.620             1
 2898263                 2.500        0.000     6.500     13.800             1
 2898349                 2.500        0.000     6.500     11.500             1

          pickup_day  pickup_hour  pickup_day_of_week_num pickup_day_of_week  \
 0                 1            0                       6             Sunday
 1                 1            0                       6             Sunday
 2                 1            0                       6             Sunday
 4                 1            0                       6             Sunday
 5                 1            0                       6             Sunday
 ...             ...          ...                     ...                ...
 2897848          30           23                       0             Monday
 2897926          30           23                       0             Monday
 2897995          30           23                       0             Monday
 2898263          30           15                       0             Monday
 2898349          30           22                       0             Monday

         pickup_date  is_weekend  trip_duration_minutes
 0        2023-01-01        True                  8.433
 1        2023-01-01        True                  6.317
 2        2023-01-01        True                 12.750
 4        2023-01-01        True                 10.833
 5        2023-01-01        True                 12.300
 ...             ...         ...                    ...
 2897848  2023-01-30       False                 22.317
 2897926  2023-01-30       False                 13.567
 2897995  2023-01-30       False                  8.133
 2898263  2023-01-30       False                  5.033
 2898349  2023-01-30       False                  3.833

 [2802015 rows x 29 columns],
          VendorID tpep_pickup_datetime tpep_dropoff_datetime  passenger_count  \
 0               1  2023-02-01 00:32:53   2023-02-01 00:34:34            2.000
 4               2  2023-02-01 00:12:28   2023-02-01 00:25:46            1.000
 5               1  2023-02-01 00:52:40   2023-02-01 01:07:18            1.000
 6               1  2023-02-01 00:12:39   2023-02-01 00:40:36            1.000
 7               1  2023-02-01 00:56:53   2023-02-01 01:00:37            1.000
 ...           ...                  ...                   ...              ...
 2745422         2  2023-02-27 21:16:23   2023-02-27 21:25:43            1.000
 2745423         2  2023-02-27 21:33:15   2023-02-27 21:36:33            1.000
 2745424         2  2023-02-27 21:40:20   2023-02-27 21:53:43            1.000
 2745425         2  2023-02-27 22:00:39   2023-02-27 22:13:49            1.000
 2749790         2  2023-02-27 22:22:19   2023-02-27 22:33:07            1.000

          trip_distance  RatecodeID store_and_fwd_flag  PULocationID  \
 0                0.300       1.000                  N           142
 4                3.220       1.000                  N           161
 5                5.100       1.000                  N           148
 6                8.900       1.000                  N           137
 7                1.200       1.000                  N           263
 ...                ...         ...                ...           ...
 2745422          1.060       1.000                  N           161
 2745423          0.480       1.000                  N           230
 2745424          3.580       1.000                  N           230
 2745425          4.730       1.000                  N           239
 2749790          1.860       1.000                  N           166

          DOLocationID  payment_type  fare_amount  extra  mta_tax  tip_amount  \
 0                 163             2        4.400  3.500    0.500       0.000
 4                 145             1       17.000  1.000    0.500       3.300
 5                 236             1       21.900  3.500    0.500       5.350
 6                 244             1       41.500  3.500    0.500       3.500
 7                 141             1        7.200  3.500    0.500       2.440
 ...               ...           ...          ...    ...      ...         ...
 2745422           170             1       10.000  0.000    0.500       2.000
 2745423           163             1        5.800  0.000    0.500       1.960
 2745424           166             1       17.000  0.000    0.500       2.000
 2745425           116             1       20.500  0.000    0.500       6.120
 2749790            74             1       12.100  0.000    0.500       1.500

          tolls_amount  improvement_surcharge  total_amount  \
 0               0.000                  1.000         9.400
 4               0.000                  1.000        25.300
 5               0.000                  1.000        32.250
 6               0.000                  1.000        50.000
 7               0.000                  1.000        14.640
 ...               ...                    ...           ...
 2745422         0.000                  1.000        16.000
 2745423         0.000                  1.000        11.760
 2745424         0.000                  1.000        23.000
 2745425         0.000                  1.000        30.620
 2749790         0.000                  1.000        15.100

          congestion_surcharge  airport_fee  abs_fare  abs_total  pickup_month  \
 0                       2.500        0.000     4.400      9.400             2
 4                       2.500        0.000    17.000     25.300             2
 5                       2.500        0.000    21.900     32.250             2
 6                       2.500        0.000    41.500     50.000             2
 7                       2.500        0.000     7.200     14.640             2
 ...                       ...          ...       ...        ...           ...
 2745422                 2.500        0.000    10.000     16.000             2
 2745423                 2.500        0.000     5.800     11.760             2
 2745424                 2.500        0.000    17.000     23.000             2
 2745425                 2.500        0.000    20.500     30.620             2
 2749790                 0.000        0.000    12.100     15.100             2

          pickup_day  pickup_hour  pickup_day_of_week_num pickup_day_of_week  \
 0                 1            0                       2          Wednesday
 4                 1            0                       2          Wednesday
 5                 1            0                       2          Wednesday
 6                 1            0                       2          Wednesday
 7                 1            0                       2          Wednesday
 ...             ...          ...                     ...                ...
 2745422          27           21                       0             Monday
 2745423          27           21                       0             Monday
 2745424          27           21                       0             Monday
 2745425          27           22                       0             Monday
 2749790          27           22                       0             Monday

         pickup_date  is_weekend  trip_duration_minutes
 0        2023-02-01       False                  1.683
 4        2023-02-01       False                 13.300
 5        2023-02-01       False                 14.633
 6        2023-02-01       False                 27.950
 7        2023-02-01       False                  3.733
 ...             ...         ...                    ...
 2745422  2023-02-27       False                  9.333
 2745423  2023-02-27       False                  3.300
 2745424  2023-02-27       False                 13.383
 2745425  2023-02-27       False                 13.167
 2749790  2023-02-27       False                 10.800

 [2648400 rows x 29 columns],
          VendorID tpep_pickup_datetime tpep_dropoff_datetime  passenger_count  \
 0               2  2023-03-01 00:06:43   2023-03-01 00:16:43            1.000
 1               2  2023-03-01 00:08:25   2023-03-01 00:39:30            2.000
 3               1  2023-03-01 00:49:37   2023-03-01 01:01:05            1.000
 4               2  2023-03-01 00:08:04   2023-03-01 00:11:06            1.000
 5               1  2023-03-01 00:09:09   2023-03-01 00:17:34            1.000
 ...           ...                  ...                   ...              ...
 3206265         2  2023-03-30 23:59:56   2023-03-31 00:23:44            6.000
 3206266         2  2023-03-30 23:58:35   2023-03-31 00:00:26            1.000
 3206437         2  2023-03-30 23:57:28   2023-03-31 00:33:21            1.000
 3206729         2  2023-03-30 23:54:53   2023-03-31 00:02:38            1.000
 3217973         2  2023-03-31 00:00:00   2023-03-31 00:00:00            1.000

          trip_distance  RatecodeID store_and_fwd_flag  PULocationID  \
 0                0.000       1.000                  N           238
 1               12.400       1.000                  N           138
 3                2.900       1.000                  N           140
 4                1.230       1.000                  N            79
 5                1.200       1.000                  N           162
 ...                ...         ...                ...           ...
 3206265         10.220       1.000                  N           230
 3206266          0.600       1.000                  N            90
 3206437         13.420       1.000                  N           132
 3206729          1.130       1.000                  N            68
 3217973          1.450       1.000                  N            50

          DOLocationID  payment_type  fare_amount  extra  mta_tax  tip_amount  \
 0                  42             2        8.600  1.000    0.500       0.000
 1                 231             1       52.700  6.000    0.500      12.540
 3                  43             1       15.600  3.500    0.500       4.100
 4                 137             1        7.200  1.000    0.500       2.440
 5                 137             1       10.000  3.500    0.500       3.000
 ...               ...           ...          ...    ...      ...         ...
 3206265            95             1       42.200  1.000    0.500      16.120
 3206266           249             1        5.100  1.000    0.500       1.000
 3206437           260             1       58.300  1.000    0.500       5.800
 3206729            68             1        9.300  1.000    0.500       2.860
 3217973            48             2       14.900  0.000    0.500       0.000

          tolls_amount  improvement_surcharge  total_amount  \
 0               0.000                  1.000        11.100
 1               0.000                  1.000        76.490
 3               0.000                  1.000        24.700
 4               0.000                  1.000        14.640
 5               0.000                  1.000        18.000
 ...               ...                    ...           ...
 3206265         6.550                  1.000        69.870
 3206266         0.000                  1.000        11.100
 3206437         0.000                  1.000        67.850
 3206729         0.000                  1.000        17.160
 3217973         0.000                  1.000        18.900

          congestion_surcharge  airport_fee  abs_fare  abs_total  pickup_month  \
 0                       0.000        0.000     8.600     11.100             3
 1                       2.500        1.250    52.700     76.490             3
 3                       2.500        0.000    15.600     24.700             3
 4                       2.500        0.000     7.200     14.640             3
 5                       2.500        0.000    10.000     18.000             3
 ...                       ...          ...       ...        ...           ...
 3206265                 2.500        0.000    42.200     69.870             3
 3206266                 2.500        0.000     5.100     11.100             3
 3206437                 0.000        1.250    58.300     67.850             3
 3206729                 2.500        0.000     9.300     17.160             3
 3217973                 2.500        0.000    14.900     18.900             3

          pickup_day  pickup_hour  pickup_day_of_week_num pickup_day_of_week  \
 0                 1            0                       2          Wednesday
 1                 1            0                       2          Wednesday
 3                 1            0                       2          Wednesday
 4                 1            0                       2          Wednesday
 5                 1            0                       2          Wednesday
 ...             ...          ...                     ...                ...
 3206265          30           23                       3           Thursday
 3206266          30           23                       3           Thursday
 3206437          30           23                       3           Thursday
 3206729          30           23                       3           Thursday
 3217973          31            0                       4             Friday

         pickup_date  is_weekend  trip_duration_minutes
 0        2023-03-01       False                 10.000
 1        2023-03-01       False                 31.083
 3        2023-03-01       False                 11.467
 4        2023-03-01       False                  3.033
 5        2023-03-01       False                  8.417
 ...             ...         ...                    ...
 3206265  2023-03-30       False                 23.800
 3206266  2023-03-30       False                  1.850
 3206437  2023-03-30       False                 35.883
 3206729  2023-03-30       False                  7.750
 3217973  2023-03-31       False                  0.000

 [3093812 rows x 29 columns],
          VendorID tpep_pickup_datetime tpep_dropoff_datetime  passenger_count  \
 0               1  2023-04-01 00:14:49   2023-04-01 00:45:01            2.000
 1               2  2023-04-01 00:00:24   2023-04-01 00:56:19            1.000
 2               1  2023-04-01 00:03:50   2023-04-01 00:14:42            2.000
 3               1  2023-04-01 00:53:18   2023-04-01 01:01:28            1.000
 4               2  2023-04-01 00:07:00   2023-04-01 00:17:16            2.000
 ...           ...                  ...                   ...              ...
 3123514         2  2023-04-29 20:28:56   2023-04-29 20:39:03            1.000
 3123515         2  2023-04-29 20:43:40   2023-04-29 20:55:13            1.000
 3123516         2  2023-04-29 20:58:22   2023-04-29 21:05:05            1.000
 3124662         2  2023-04-29 21:18:46   2023-04-29 21:26:21            1.000
 3124663         2  2023-04-29 21:51:00   2023-04-29 22:01:35            1.000

          trip_distance  RatecodeID store_and_fwd_flag  PULocationID  \
 0                4.900       1.000                  N            48
 1               21.890       2.000                  N           132
 2                1.300       1.000                  N           148
 3                1.500       1.000                  N           249
 4                1.490       1.000                  N           158
 ...                ...         ...                ...           ...
 3123514          2.150       1.000                  N           163
 3123515          3.580       1.000                  N           236
 3123516          1.830       1.000                  N           224
 3124662          1.170       1.000                  N           107
 3124663          2.050       1.000                  N           162

          DOLocationID  payment_type  fare_amount  extra  mta_tax  tip_amount  \