In [1]:
import numpy as np
import pandas as pd
import pyarrow as pa
import matplotlib.pyplot as plt
import seaborn as sns
from IPython.display import display

pd.set_option("display.max_columns", None)
pd.set_option('display.float_format', lambda x: '%.3f' % x)

In [2]:
import sys
from pathlib import Path

# Add the project root directory to sys.path
# (Adjust .parent counts depending on how deep your notebook is)
project_root = Path.cwd().parent
if str(project_root) not in sys.path:
    sys.path.append(str(project_root))

# Now import directly from your folder structure
from scripts.data_cleaning import clean_data

In [3]:
month_name_num = {
    "Jan": "01",
    "Feb": "02",
    "Mar": "03",
    "Apr": "04",
    "May": "05",
    "Jun": "06",
    "Jul": "07",
    "Aug": "08",
    "Sep": "09",
    "Oct": "10",
    "Nov": "11",
    "Dec": "12",
}

In [4]:
monthly_data = {}

In [5]:
for key, value in month_name_num.items():
    df = pd.read_parquet(f"https://d37ci6vzurychx.cloudfront.net/trip-data/yellow_tripdata_2023-{value}.parquet")
    cleaned_df = clean_data(df, int(value))
    monthly_data[key] = cleaned_df

In [6]:
for month, datasets in monthly_data.items():
    cleaned_df = datasets[0]
    print(month, cleaned_df.columns.tolist())

Jan ['VendorID', 'tpep_pickup_datetime', 'tpep_dropoff_datetime', 'passenger_count', 'trip_distance', 'RatecodeID', 'store_and_fwd_flag', 'PULocationID', 'DOLocationID', 'payment_type', 'fare_amount', 'extra', 'mta_tax', 'tip_amount', 'tolls_amount', 'improvement_surcharge', 'total_amount', 'congestion_surcharge', 'airport_fee', 'abs_fare', 'abs_total']
Feb ['VendorID', 'tpep_pickup_datetime', 'tpep_dropoff_datetime', 'passenger_count', 'trip_distance', 'RatecodeID', 'store_and_fwd_flag', 'PULocationID', 'DOLocationID', 'payment_type', 'fare_amount', 'extra', 'mta_tax', 'tip_amount', 'tolls_amount', 'improvement_surcharge', 'total_amount', 'congestion_surcharge', 'airport_fee', 'abs_fare', 'abs_total']
Mar ['VendorID', 'tpep_pickup_datetime', 'tpep_dropoff_datetime', 'passenger_count', 'trip_distance', 'RatecodeID', 'store_and_fwd_flag', 'PULocationID', 'DOLocationID', 'payment_type', 'fare_amount', 'extra', 'mta_tax', 'tip_amount', 'tolls_amount', 'improvement_surcharge', 'total_amount', 'congestion_surcharge', 'airport_fee', 'abs_fare', 'abs_total']
Apr ['VendorID', 'tpep_pickup_datetime', 'tpep_dropoff_datetime', 'passenger_count', 'trip_distance', 'RatecodeID', 'store_and_fwd_flag', 'PULocationID', 'DOLocationID', 'payment_type', 'fare_amount', 'extra', 'mta_tax', 'tip_amount', 'tolls_amount', 'improvement_surcharge', 'total_amount', 'congestion_surcharge', 'airport_fee', 'abs_fare', 'abs_total']
May ['VendorID', 'tpep_pickup_datetime', 'tpep_dropoff_datetime', 'passenger_count', 'trip_distance', 'RatecodeID', 'store_and_fwd_flag', 'PULocationID', 'DOLocationID', 'payment_type', 'fare_amount', 'extra', 'mta_tax', 'tip_amount', 'tolls_amount', 'improvement_surcharge', 'total_amount', 'congestion_surcharge', 'airport_fee', 'abs_fare', 'abs_total']
Jun ['VendorID', 'tpep_pickup_datetime', 'tpep_dropoff_datetime', 'passenger_count', 'trip_distance', 'RatecodeID', 'store_and_fwd_flag', 'PULocationID', 'DOLocationID', 'payment_type', 'fare_amount', 'extra', 'mta_tax', 'tip_amount', 'tolls_amount', 'improvement_surcharge', 'total_amount', 'congestion_surcharge', 'airport_fee', 'abs_fare', 'abs_total']
Jul ['VendorID', 'tpep_pickup_datetime', 'tpep_dropoff_datetime', 'passenger_count', 'trip_distance', 'RatecodeID', 'store_and_fwd_flag', 'PULocationID', 'DOLocationID', 'payment_type', 'fare_amount', 'extra', 'mta_tax', 'tip_amount', 'tolls_amount', 'improvement_surcharge', 'total_amount', 'congestion_surcharge', 'airport_fee', 'abs_fare', 'abs_total']
Aug ['VendorID', 'tpep_pickup_datetime', 'tpep_dropoff_datetime', 'passenger_count', 'trip_distance', 'RatecodeID', 'store_and_fwd_flag', 'PULocationID', 'DOLocationID', 'payment_type', 'fare_amount', 'extra', 'mta_tax', 'tip_amount', 'tolls_amount', 'improvement_surcharge', 'total_amount', 'congestion_surcharge', 'airport_fee', 'abs_fare', 'abs_total']
Sep ['VendorID', 'tpep_pickup_datetime', 'tpep_dropoff_datetime', 'passenger_count', 'trip_distance', 'RatecodeID', 'store_and_fwd_flag', 'PULocationID', 'DOLocationID', 'payment_type', 'fare_amount', 'extra', 'mta_tax', 'tip_amount', 'tolls_amount', 'improvement_surcharge', 'total_amount', 'congestion_surcharge', 'airport_fee', 'abs_fare', 'abs_total']
Oct ['VendorID', 'tpep_pickup_datetime', 'tpep_dropoff_datetime', 'passenger_count', 'trip_distance', 'RatecodeID', 'store_and_fwd_flag', 'PULocationID', 'DOLocationID', 'payment_type', 'fare_amount', 'extra', 'mta_tax', 'tip_amount', 'tolls_amount', 'improvement_surcharge', 'total_amount', 'congestion_surcharge', 'airport_fee', 'abs_fare', 'abs_total']
Nov ['VendorID', 'tpep_pickup_datetime', 'tpep_dropoff_datetime', 'passenger_count', 'trip_distance', 'RatecodeID', 'store_and_fwd_flag', 'PULocationID', 'DOLocationID', 'payment_type', 'fare_amount', 'extra', 'mta_tax', 'tip_amount', 'tolls_amount', 'improvement_surcharge', 'total_amount', 'congestion_surcharge', 'airport_fee', 'abs_fare', 'abs_total']
Dec ['VendorID', 'tpep_pickup_datetime', 'tpep_dropoff_datetime', 'passenger_count', 'trip_distance', 'RatecodeID', 'store_and_fwd_flag', 'PULocationID', 'DOLocationID', 'payment_type', 'fare_amount', 'extra', 'mta_tax', 'tip_amount', 'tolls_amount', 'improvement_surcharge', 'total_amount', 'congestion_surcharge', 'airport_fee', 'abs_fare', 'abs_total']

In [7]:
df_jan = monthly_data['Jan'][0]

In [8]:
df_jan.head()

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge,airport_fee,abs_fare,abs_total
0,2,2023-01-01 00:32:10,2023-01-01 00:40:36,1.000,0.970,1.000,N,161,141,2,9.300,1.000,0.500,0.000,0.000,1.000,14.300,2.500,0.000,9.300,14.300
1,2,2023-01-01 00:55:08,2023-01-01 01:01:27,1.000,1.100,1.000,N,43,237,1,7.900,1.000,0.500,4.000,0.000,1.000,16.900,2.500,0.000,7.900,16.900
2,2,2023-01-01 00:25:04,2023-01-01 00:37:49,1.000,2.510,1.000,N,48,238,1,14.900,1.000,0.500,15.000,0.000,1.000,34.900,2.500,0.000,14.900,34.900
4,2,2023-01-01 00:10:29,2023-01-01 00:21:19,1.000,1.430,1.000,N,107,79,1,11.400,1.000,0.500,3.280,0.000,1.000,19.680,2.500,0.000,11.400,19.680
5,2,2023-01-01 00:50:34,2023-01-01 01:02:52,1.000,1.840,1.000,N,161,137,1,12.800,1.000,0.500,10.000,0.000,1.000,27.800,2.500,0.000,12.800,27.800

In [14]:
df_jan['pickup_month'] = df_jan['tpep_pickup_datetime'].dt.month
df_jan['pickup_day'] = df_jan['tpep_pickup_datetime'].dt.day
df_jan['pickup_hour'] = df_jan['tpep_pickup_datetime'].dt.hour
df_jan['pickup_day_of_week_num'] = df_jan['tpep_pickup_datetime'].dt.day_of_week
df_jan['pickup_day_of_week'] = df_jan['tpep_pickup_datetime'].dt.day_name()
df_jan['pickup_date'] = df_jan['tpep_pickup_datetime'].dt.date
df_jan["is_weekend"] = (
    df_jan["pickup_day_of_week_num"] >= 5
)
df_jan['trip_duration_minutes'] = (
        df_jan["tpep_dropoff_datetime"]
        - df_jan["tpep_pickup_datetime"]
    ).dt.total_seconds() / 60

In [15]:
df_jan.head()

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge,airport_fee,abs_fare,abs_total,pickup_month,pickup_day,pickup_hour,pickup_day_of_week,pickup_date,pickup_day_of_week_num,is_weekend,trip_duration_minutes
0,2,2023-01-01 00:32:10,2023-01-01 00:40:36,1.000,0.970,1.000,N,161,141,2,9.300,1.000,0.500,0.000,0.000,1.000,14.300,2.500,0.000,9.300,14.300,1,1,0,Sunday,2023-01-01,6,True,8.433
1,2,2023-01-01 00:55:08,2023-01-01 01:01:27,1.000,1.100,1.000,N,43,237,1,7.900,1.000,0.500,4.000,0.000,1.000,16.900,2.500,0.000,7.900,16.900,1,1,0,Sunday,2023-01-01,6,True,6.317
2,2,2023-01-01 00:25:04,2023-01-01 00:37:49,1.000,2.510,1.000,N,48,238,1,14.900,1.000,0.500,15.000,0.000,1.000,34.900,2.500,0.000,14.900,34.900,1,1,0,Sunday,2023-01-01,6,True,12.750
4,2,2023-01-01 00:10:29,2023-01-01 00:21:19,1.000,1.430,1.000,N,107,79,1,11.400,1.000,0.500,3.280,0.000,1.000,19.680,2.500,0.000,11.400,19.680,1,1,0,Sunday,2023-01-01,6,True,10.833
5,2,2023-01-01 00:50:34,2023-01-01 01:02:52,1.000,1.840,1.000,N,161,137,1,12.800,1.000,0.500,10.000,0.000,1.000,27.800,2.500,0.000,12.800,27.800,1,1,0,Sunday,2023-01-01,6,True,12.300

In [16]:
df_jan.describe()

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,PULocationID,DOLocationID,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge,airport_fee,abs_fare,abs_total,pickup_month,pickup_day,pickup_hour,pickup_day_of_week_num,trip_duration_minutes
count,2802015.000,2802015,2802015,2802015.000,2802015.000,2802015.000,2802015.000,2802015.000,2802015.000,2802015.000,2802015.000,2802015.000,2802015.000,2802015.000,2802015.000,2802015.000,2802015.000,2802015.000,2802015.000,2802015.000,2802015.000,2802015.000,2802015.000,2802015.000,2802015.000
mean,1.741,2023-01-16 12:49:22.802829,2023-01-16 13:05:07.382481,1.390,3.399,1.506,166.372,164.429,1.189,18.680,1.561,0.496,3.421,0.536,0.999,27.498,2.312,0.111,18.680,27.498,1.000,15.924,14.151,3.070,15.743
min,1.000,2023-01-01 00:00:05,2023-01-01 00:03:28,1.000,0.000,1.000,1.000,1.000,1.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,1.000,1.000,0.000,0.000,-29.200
25%,1.000,2023-01-09 11:55:40,2023-01-09 12:11:18.500000,1.000,1.080,1.000,132.000,114.000,1.000,8.600,0.000,0.500,1.000,0.000,1.000,15.480,2.500,0.000,8.600,15.480,1.000,9.000,11.000,1.000,7.133
50%,2.000,2023-01-16 15:45:33,2023-01-16 16:01:53,1.000,1.800,1.000,162.000,162.000,1.000,12.800,1.000,0.500,2.800,0.000,1.000,20.160,2.500,0.000,12.800,20.160,1.000,16.000,15.000,3.000,11.500
75%,2.000,2023-01-23 19:28:44,2023-01-23 19:41:41,1.000,3.340,1.000,234.000,234.000,1.000,20.500,2.500,0.500,4.200,0.000,1.000,28.800,2.500,0.000,20.500,28.800,1.000,23.000,19.000,5.000,18.250
max,2.000,2023-01-30 23:59:58,2023-01-31 21:58:49,9.000,96.700,99.000,265.000,265.000,4.000,999.000,12.500,53.160,380.800,196.990,1.000,1000.000,2.500,1.250,999.000,1000.000,1.000,30.000,23.000,6.000,10029.183
std,0.438,NaN,NaN,0.890,4.423,6.541,64.126,69.980,0.413,17.448,1.776,0.054,3.855,2.031,0.033,21.761,0.659,0.355,17.448,21.761,0.000,8.410,5.772,1.988,43.838

In [17]:
df_jan[df_jan['trip_duration_minutes'] < 0]

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge,airport_fee,abs_fare,abs_total,pickup_month,pickup_day,pickup_hour,pickup_day_of_week,pickup_date,pickup_day_of_week_num,is_weekend,trip_duration_minutes
1839180,1,2023-01-20 13:35:00,2023-01-20 13:05:48,1.000,0.800,99.000,N,227,14,1,16.500,0.000,0.500,0.000,0.000,1.000,18.000,0.000,0.000,16.500,18.000,1,20,13,Friday,2023-01-20,4,False,-29.200
2124414,1,2023-01-23 10:43:58,2023-01-23 10:29:26,1.000,2.400,99.000,N,102,82,1,21.500,0.000,0.500,0.000,0.000,1.000,23.000,0.000,0.000,21.500,23.000,1,23,10,Monday,2023-01-23,0,False,-14.533
2218504,1,2023-01-24 11:00:00,2023-01-24 10:40:48,1.000,0.400,99.000,N,247,169,1,15.500,0.000,0.500,0.000,0.000,1.000,17.000,0.000,0.000,15.500,17.000,1,24,11,Tuesday,2023-01-24,1,False,-19.200

## Need to go back to cleaning. Some dates are reversed for pickup and dropoff.