# NYC Taxi Analysis

## Initial Imports

In [10]:
import numpy as np
import pandas as pd
import pyarrow as pa
import matplotlib.pyplot as plt
import seaborn as sns
from IPython.display import display

pd.set_option("display.max_columns", None)
pd.set_option('display.float_format', lambda x: '%.3f' % x)

## Initial Data Loading

Only the first 3 months to get a feel for the data, then will make a cleaning/transforming functions to run on all the months.

In [5]:
df_jan = pd.read_parquet("https://d37ci6vzurychx.cloudfront.net/trip-data/yellow_tripdata_2023-01.parquet")
df_feb = pd.read_parquet("https://d37ci6vzurychx.cloudfront.net/trip-data/yellow_tripdata_2023-02.parquet")
df_mar = pd.read_parquet("https://d37ci6vzurychx.cloudfront.net/trip-data/yellow_tripdata_2023-03.parquet")

In [13]:
def display_info(df):
    print("Info")
    print("=" * 20)
    display(df.info())
    print("Describe")
    print("=" * 20)
    display(df.describe())
    print("Null Values")
    print("=" * 20)
    display(df.isna().sum())

In [14]:
display_info(df_jan)

Info
====================
<class 'pandas.DataFrame'>
RangeIndex: 3066766 entries, 0 to 3066765
Data columns (total 19 columns):
 #   Column                 Dtype
---  ------                 -----
 0   VendorID               int64
 1   tpep_pickup_datetime   datetime64[us]
 2   tpep_dropoff_datetime  datetime64[us]
 3   passenger_count        float64
 4   trip_distance          float64
 5   RatecodeID             float64
 6   store_and_fwd_flag     str
 7   PULocationID           int64
 8   DOLocationID           int64
 9   payment_type           int64
 10  fare_amount            float64
 11  extra                  float64
 12  mta_tax                float64
 13  tip_amount             float64
 14  tolls_amount           float64
 15  improvement_surcharge  float64
 16  total_amount           float64
 17  congestion_surcharge   float64
 18  airport_fee            float64
dtypes: datetime64[us](2), float64(12), int64(4), str(1)
memory usage: 447.8 MB

None

Describe
====================

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,PULocationID,DOLocationID,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge,airport_fee
count,3066766.000,3066766,3066766,2995023.000,3066766.000,2995023.000,3066766.000,3066766.000,3066766.000,3066766.000,3066766.000,3066766.000,3066766.000,3066766.000,3066766.000,3066766.000,2995023.000,2995023.000
mean,1.730,2023-01-17 00:22:26.288164,2023-01-17 00:38:06.427874,1.363,3.847,1.497,166.398,164.393,1.194,18.367,1.538,0.488,3.368,0.518,0.982,27.020,2.274,0.107
min,1.000,2008-12-31 23:01:42,2009-01-01 14:29:11,0.000,0.000,1.000,1.000,1.000,0.000,-900.000,-7.500,-0.500,-96.220,-65.000,-1.000,-751.000,-2.500,-1.250
25%,1.000,2023-01-09 16:21:57.250000,2023-01-09 16:37:06,1.000,1.060,1.000,132.000,114.000,1.000,8.600,0.000,0.500,1.000,0.000,1.000,15.400,2.500,0.000
50%,2.000,2023-01-17 08:42:29.500000,2023-01-17 08:58:30.500000,1.000,1.800,1.000,162.000,162.000,1.000,12.800,1.000,0.500,2.720,0.000,1.000,20.160,2.500,0.000
75%,2.000,2023-01-24 16:26:27,2023-01-24 16:42:49,1.000,3.330,1.000,234.000,234.000,1.000,20.500,2.500,0.500,4.200,0.000,1.000,28.700,2.500,0.000
max,2.000,2023-02-01 00:56:53,2023-02-02 09:28:47,9.000,258928.150,99.000,265.000,265.000,4.000,1160.100,12.500,53.160,380.800,196.990,1.000,1169.400,2.500,1.250
std,0.444,NaN,NaN,0.896,249.584,6.475,64.244,69.944,0.529,17.808,1.790,0.103,3.827,2.018,0.183,22.164,0.772,0.356

Null Values
====================

VendorID                     0
tpep_pickup_datetime         0
tpep_dropoff_datetime        0
passenger_count          71743
trip_distance                0
RatecodeID               71743
store_and_fwd_flag       71743
PULocationID                 0
DOLocationID                 0
payment_type                 0
fare_amount                  0
extra                        0
mta_tax                      0
tip_amount                   0
tolls_amount                 0
improvement_surcharge        0
total_amount                 0
congestion_surcharge     71743
airport_fee              71743
dtype: int64

In [15]:
display_info(df_feb)

Info
====================
<class 'pandas.DataFrame'>
RangeIndex: 2913955 entries, 0 to 2913954
Data columns (total 19 columns):
 #   Column                 Dtype
---  ------                 -----
 0   VendorID               int32
 1   tpep_pickup_datetime   datetime64[us]
 2   tpep_dropoff_datetime  datetime64[us]
 3   passenger_count        float64
 4   trip_distance          float64
 5   RatecodeID             float64
 6   store_and_fwd_flag     str
 7   PULocationID           int32
 8   DOLocationID           int32
 9   payment_type           int64
 10  fare_amount            float64
 11  extra                  float64
 12  mta_tax                float64
 13  tip_amount             float64
 14  tolls_amount           float64
 15  improvement_surcharge  float64
 16  total_amount           float64
 17  congestion_surcharge   float64
 18  Airport_fee            float64
dtypes: datetime64[us](2), float64(12), int32(3), int64(1), str(1)
memory usage: 392.1 MB

None

Describe
====================

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,PULocationID,DOLocationID,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge,Airport_fee
count,2913955.000,2913955,2913955,2837138.000,2913955.000,2837138.000,2913955.000,2913955.000,2913955.000,2913955.000,2913955.000,2913955.000,2913955.000,2913955.000,2913955.000,2913955.000,2837138.000,2837138.000
mean,1.731,2023-02-15 00:38:01.639923,2023-02-15 00:54:02.594499,1.353,3.868,1.515,166.257,164.232,1.183,18.220,1.560,0.488,3.385,0.511,0.981,26.898,2.285,0.097
min,1.000,2008-12-31 23:05:06,2008-12-31 23:31:24,0.000,0.000,1.000,1.000,1.000,0.000,-754.050,-7.500,-0.500,-93.000,-57.000,-1.000,-757.550,-2.500,-1.250
25%,1.000,2023-02-08 08:43:13,2023-02-08 08:59:34,1.000,1.060,1.000,132.000,113.000,1.000,8.600,0.000,0.500,1.000,0.000,1.000,15.480,2.500,0.000
50%,2.000,2023-02-14 22:33:21,2023-02-14 22:48:15,1.000,1.790,1.000,162.000,162.000,1.000,12.800,1.000,0.500,2.800,0.000,1.000,20.200,2.500,0.000
75%,2.000,2023-02-22 08:34:18,2023-02-22 08:50:06,1.000,3.300,1.000,234.000,234.000,1.000,20.300,2.500,0.500,4.200,0.000,1.000,28.700,2.500,0.000
max,6.000,2023-03-07 13:01:28,2023-03-07 13:11:17,9.000,335004.330,99.000,265.000,265.000,4.000,2203.100,20.800,4.000,482.900,109.900,1.000,2208.100,2.750,1.250
std,0.452,NaN,NaN,0.889,268.427,6.633,64.132,69.754,0.530,17.498,1.793,0.101,3.838,2.024,0.187,21.841,0.761,0.339

Null Values
====================

VendorID                     0
tpep_pickup_datetime         0
tpep_dropoff_datetime        0
passenger_count          76817
trip_distance                0
RatecodeID               76817
store_and_fwd_flag       76817
PULocationID                 0
DOLocationID                 0
payment_type                 0
fare_amount                  0
extra                        0
mta_tax                      0
tip_amount                   0
tolls_amount                 0
improvement_surcharge        0
total_amount                 0
congestion_surcharge     76817
Airport_fee              76817
dtype: int64

In [16]:
display_info(df_mar)

Info
====================
<class 'pandas.DataFrame'>
RangeIndex: 3403766 entries, 0 to 3403765
Data columns (total 19 columns):
 #   Column                 Dtype
---  ------                 -----
 0   VendorID               int32
 1   tpep_pickup_datetime   datetime64[us]
 2   tpep_dropoff_datetime  datetime64[us]
 3   passenger_count        float64
 4   trip_distance          float64
 5   RatecodeID             float64
 6   store_and_fwd_flag     str
 7   PULocationID           int32
 8   DOLocationID           int32
 9   payment_type           int64
 10  fare_amount            float64
 11  extra                  float64
 12  mta_tax                float64
 13  tip_amount             float64
 14  tolls_amount           float64
 15  improvement_surcharge  float64
 16  total_amount           float64
 17  congestion_surcharge   float64
 18  Airport_fee            float64
dtypes: datetime64[us](2), float64(12), int32(3), int64(1), str(1)
memory usage: 458.0 MB

None

Describe
====================

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,PULocationID,DOLocationID,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge,Airport_fee
count,3403766.000,3403766,3403766,3316147.000,3403766.000,3316147.000,3403766.000,3403766.000,3403766.000,3403766.000,3403766.000,3403766.000,3403766.000,3403766.000,3403766.000,3403766.000,3316147.000,3316147.000
mean,1.725,2023-03-16 11:32:30.578784,2023-03-16 11:49:23.487819,1.351,3.904,1.624,165.454,164.100,1.187,18.908,1.629,0.487,3.495,0.567,0.981,27.803,2.275,0.104
min,1.000,2001-01-01 00:06:49,2001-01-01 14:13:51,0.000,0.000,1.000,1.000,1.000,0.000,-959.900,-7.500,-0.500,-80.000,-73.300,-1.000,-982.950,-2.500,-1.250
25%,1.000,2023-03-08 18:48:02,2023-03-08 19:04:47,1.000,1.050,1.000,132.000,114.000,1.000,9.300,0.000,0.500,1.000,0.000,1.000,15.700,2.500,0.000
50%,2.000,2023-03-16 12:18:33,2023-03-16 12:38:00,1.000,1.790,1.000,162.000,162.000,1.000,13.500,1.000,0.500,2.800,0.000,1.000,20.600,2.500,0.000
75%,2.000,2023-03-24 08:55:29.750000,2023-03-24 09:11:11.500000,1.000,3.380,1.000,233.000,234.000,1.000,21.200,2.500,0.500,4.340,0.000,1.000,29.760,2.500,0.000
max,6.000,2023-04-05 20:17:42,2023-04-05 20:35:28,9.000,216986.960,99.000,265.000,265.000,5.000,2100.000,13.750,4.000,984.300,177.000,1.000,2100.000,2.500,1.250
std,0.459,NaN,NaN,0.886,191.687,7.359,63.740,69.673,0.533,18.256,1.843,0.102,3.996,2.122,0.189,22.866,0.775,0.350

Null Values
====================

VendorID                     0
tpep_pickup_datetime         0
tpep_dropoff_datetime        0
passenger_count          87619
trip_distance                0
RatecodeID               87619
store_and_fwd_flag       87619
PULocationID                 0
DOLocationID                 0
payment_type                 0
fare_amount                  0
extra                        0
mta_tax                      0
tip_amount                   0
tolls_amount                 0
improvement_surcharge        0
total_amount                 0
congestion_surcharge     87619
Airport_fee              87619
dtype: int64

Looking at the above information, the 3 dataframes are mostly similar:
- They all have the same 19 columns (with some formatting differences)
- The same 5 columns have missing data each time
- In those 5 columns, they all have the same amount of missing data (within their respective datasets)

## Next Steps 

Perform following data cleaning on January 2023 to make function for remaining months. 

1. Filter out data outside of the dataset's month
2. Check for patterns of missing data (Similar VendorIds, payment_types, etc.)
    - Check the data dictionary for assistance
3. Impute congestion surcharge and airport fees with 0, as null values likely mean they were not congested and/or airport trips